name: Build and Deploy SRB2 Web Port

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Emscripten environment
        uses: trzeci/emscripten@v1.39.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make build-essential
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Build SRB2
        run: |
          emcmake cmake .
          emmake make
          emcc -O2 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 -o srb2.html src/main.c

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust to your build output directory
